# Generated by Django 3.2.5 on 2021-07-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('data_finish', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
